import React from 'react';
const columns=[{
  title: '客户订单号',
  dataIndex: 'boxCode',
  key: 'boxCode',
  width: 120,
}, {
  title: '寄件人',
  dataIndex: 'sender',
  key: 'sender',
  width: 100,
}, {
  title: '寄件人电话号码',
  dataIndex: 'senderPhone',
  key: 'senderPhone',
  width: 100,
},  {
  title: '寄件人邮编',
  dataIndex: 'senderPostcode',
  key: 'senderPostcode',
  width: 70,
}, {
  title: '寄件人地址',
  dataIndex: 'senderAddress',
  key: 'senderAddress',
  width: 100,
  render: (text, record) => (  //塞入内容
    <div className="ellipsis" style={{width:79}} title={record.senderAddress}>{record.senderAddress}</div>
  ),
}, {
  title: '收件省/直辖市',
  dataIndex: 'recipientsProvince',
  key: 'recipientsProvince',
  width: 120,
}, {
  title: '收件城市',
  dataIndex: 'recipientsCity',
  key: 'recipientsCity',
  width: 100,
}, {
  title: '收件区域',
  dataIndex: 'recipientsDistrict',
  key: 'recipientsDistrict',
  width: 100,
}, {
  title: '收件人',
  dataIndex: 'recipientsName',
  key: 'recipientsName',
  width: 100,
}, {
  title: '收件人邮编',
  dataIndex: 'postcode',
  key: 'postcode',
  width: 70,
}, {
  title: '收件人地址',
  dataIndex: 'recipientsAddress',
  key: 'recipientsAddress',
  width: 100,
}, {
  title: '收件人电话号码',
  dataIndex: 'recipientsPhone',
  key: 'recipientsPhone',
  width: 110,
}, {
  title: '实际重量',
  dataIndex: 'boxKg',
  key: 'boxKg',
  width: 60,
}, {
  title: '原产地区',
  dataIndex: 'countryOrigin',
  key: 'countryOrigin',
  width: 60,
}, {
  title: '是否代缴关税',
  dataIndex: 'hasPreaid',
  key: 'hasPreaid',
  width: 80,
  render: (text, record) => (  //塞入内容
    <span>{record.hasPreaid===0 ? "否":"是"}</span>
  ),
}, {
  title: '行邮税号',
  dataIndex: 'taxNumber',
  key: 'taxNumber',
  width: 100,
}, {
  title: '物品名称',
  dataIndex: 'name',
  key: 'name',
  width: 80,
}, {
  title: '规格型号',
  dataIndex: 'specification',
  key: 'specification',
  width: 80,
}, {
  title: '物品数量',
  dataIndex: 'number',
  key: 'number',
  width: 80,
}, {
  title: '计量单位',
  dataIndex: 'modelNumber',
  key: 'modelNumber',
  width: 80,
}, {
  title: '物品单价',
  dataIndex: 'price',
  key: 'price',
  width: 80,
},
  {
    title: '行邮税号',
    dataIndex: 'taxNumber2',
    key: 'taxNumber2',
    width: 100,
  }, {
    title: '物品名称',
    dataIndex: 'name2',
    key: 'name2',
    width: 80,
  }, {
    title: '规格型号',
    dataIndex: 'specification2',
    key: 'specification2',
    width: 80,
  }, {
    title: '物品数量',
    dataIndex: 'number2',
    key: 'number2',
    width: 80,
  }, {
    title: '计量单位',
    dataIndex: 'modelNumber2',
    key: 'modelNumber2',
    width: 80,
  }, {
    title: '物品单价',
    dataIndex: 'price2',
    key: 'price2',
    width: 80,
  },
  {
    title: '行邮税号',
    dataIndex: 'taxNumber3',
    key: 'taxNumber3',
    width: 100,
  }, {
    title: '物品名称',
    dataIndex: 'name3',
    key: 'name3',
    width: 80,
  }, {
    title: '规格型号',
    dataIndex: 'specification3',
    key: 'specification3',
    width: 80,
  }, {
    title: '物品数量',
    dataIndex: 'number3',
    key: 'number3',
    width: 80,
  }, {
    title: '计量单位',
    dataIndex: 'modelNumber3',
    key: 'modelNumber3',
    width: 80,
  }, {
    title: '物品单价',
    dataIndex: 'price3',
    key: 'price3',
    width: 80,
  }];
export default columns;